
# Please note that empty file or directory fields are interpreted as not
# available and represented by None. If you want to specify current working
# directory, use '.'

# What precision is treated as equal when comparing annotation boundaries.
epsilon: 0.00001

# Used in filtering sound signals before beep detection.
mains_frequency: 50

# Default parameters for a data run. Unless you happen to be running example
# tongue data, you should probably change these. Do it by copying the file and
# giving a commandline argument.
data_run_parameter_file: configuration/data_run_parameters.yaml

# GUI setup parameters
gui_parameter_file: configuration/gui_parameters.yaml

publish_parameter_file: configuration/publish_parameters.yaml